---
driver:
  name: vagrant
  customize:
    memory: 1024
    cpus: 2

provisioner:
  name: chef_solo
  require_chef_omnibus: 12.3.0

platforms:
  - name: ubuntu-14.04
  - name: fedora-20
  - name: centos-7.0

suites:
  - name: default
    run_list:
      - "recipe[stackstorm::bundle]"
    attributes:
