---
settings:
  parallel: true

driver:
  name: docker
  privileged: true
  use_sudo: false

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 14.4.56

verifier:
  name: inspec

platforms:
- name: ubuntu-14.04
  driver:
    image: ubuntu-upstart:14.04
    platform: ubuntu
    disable_upstart: false
    run_command: /sbin/init
    provision_command:
      - /usr/bin/apt-get update && /usr/bin/apt-get install -y apt-transport-https net-tools initscripts libpq5 libpq-dev
- name: centos-7.5
  driver:
    image: centos:7
    platform: rhel
    run_command: /usr/lib/systemd/systemd
    provision_command:
      - /bin/yum install -y initscripts net-tools wget logrotate postgresql-libs

suites:
  - name: default
    run_list:
      - "recipe[stackstorm::bundle]"
