---
driver:
  name: vagrant
  customize:
    memory: 1024
    cpus: 2

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 14.4.56

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04
  - name: centos-7.5

suites:
  - name: default
    run_list:
      - "recipe[stackstorm::bundle]"
