# Use Travis's cointainer based infrastructure
sudo: required
services: docker

addons:
 apt:
   sources:
     - chef-stable-precise
   packages:
     - chefdk

# Don't `bundle install`
install: echo "skip bundle install"

branches:
  only:
    - master

env:
  matrix:
    - SUITE=default
    - SUITE=integration:kitchen:default-ubuntu-1404
    - SUITE=integration:kitchen:default-centos-72

before_script:
  # https://github.com/zuazo/kitchen-in-travis-native/issues/1#issuecomment-142455888
  - sudo iptables -L DOCKER || sudo iptables -N DOCKER
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - /opt/chefdk/bin/chef gem install kitchen-docker

script:
  - /opt/chefdk/bin/chef --version
  - /opt/chefdk/bin/cookstyle --version
  - /opt/chefdk/bin/foodcritic --version
  - /opt/chefdk/bin/kitchen --version
  - KITCHEN_LOCAL_YAML=.kitchen.docker.yml /opt/chefdk/bin/chef exec rake ${SUITE}

notifications:
  # Post build failures to '#chef' channel in 'stackstorm-community' Slack
  slack:
    rooms:
      - secure: O+o2FvLubrlKelWc1uvtcpLZgyQIBOoRGepZH2eKeguinGiXqaic0GK5KUthFdJJtmn3uT+brGyug08wgmSQKa+VoFEPJwHCIYTL2ZnGoggtJcbv8FU0c2sa1DJ1gSH4Q8PGzuwKuW67ExfYQYPwciyJ3RjmoYoIouB1pbqwmgk=
    on_pull_requests: false
    on_success: change # default: always
    on_failure: always # default: always
