name             'stackstorm'
maintainer       'StackStorm (st2-dev)'
maintainer_email 'info@stackstorm.com'
license          'Apache 2.0'
description      'Installs/Configures stackstorm'
long_description 'Installs/Configures stackstorm'
version          '0.2.5'

supports 'debian'
supports 'ubuntu'
supports 'redhat'
supports 'centos'
supports 'amazon'

depends 'sudo'
depends 'build-essential'
depends 'python'
depends 'git'
depends 'gdebi'
depends 'rabbitmq', '>= 3.12.0'
depends 'mongodb'
depends 'mysql'
depends 'openstack-mistral'
depends 'apt'
depends 'yum'
depends 'yum-epel'
depends 'hostsfile'

source_url 'https://github.com/StackStorm/chef-stackstorm' if respond_to?(:source_url)
issues_url 'https://github.com/StackStorm/chef-stackstorm/issues' if respond_to?(:issues_url)
