name             'stackstorm'
maintainer       'StackStorm (st2-dev)'
maintainer_email 'info@stackstorm.com'
license          'Apache 2.0'
description      'Installs/Configures stackstorm'
long_description 'Installs/Configures stackstorm'
version          '0.2.1'

supports 'debian'
supports 'ubuntu'
supports 'redhat'
supports 'centos'
supports 'amazon'

depends 'sudo'
depends 'build-essential'
depends 'python'
depends 'git'
depends 'gdebi'
depends 'rabbitmq'
depends 'mongodb'
depends 'yum-epel'
depends 'mysql'
depends 'openstack-mistral'
